/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Machine.MIR;
import Tools.MIC1;
import static Tools.MIC1.objectLock;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Thiago G Goncalves
 */
public class GUI extends javax.swing.JFrame {

    public static boolean mic1_gui = true;
    public static boolean register_memory_gui = true;
    String code = "";
    Decoder instructs;
    String opCodeAnswer = "";
    ArrayList<MIR> opCodeContainer = new ArrayList<>();
    int countLine = 1;
    boolean addLineNumber = false;

    /**
     * Creates new form GUI
     */
    public GUI() {

        instructs = new Decoder();
        initComponents();

        this.set();

        amuxArea.setOpaque(false);
        alatchArea.setOpaque(false);
        blatchArea.setOpaque(false);
        machineArea.setOpaque(false);
        jPanel4.setOpaque(false);
        jPanel8.setOpaque(false);
        memory.setOpaque(false);
        abusArrowArea.add(new ArrowPanel(Direction.DOWN, abusArrowArea.getSize().height));
        bbusArrowArea.add(new ArrowPanel(Direction.DOWN, bbusArrowArea.getSize().height));
        alatchAmuxArrowArea.add(new ArrowPanel(Direction.DOWN, alatchAmuxArrowArea.getSize().height));
        blatchArrowArea.add(new ArrowPanel(Direction.DOWN, blatchArrowArea.getSize().height));
        amuxAluArrowArea.add(new ArrowPanel(Direction.DOWN, amuxAluArrowArea.getSize().height));
        aluShifterArrowArea.add(new ArrowPanel(Direction.DOWN, aluShifterArrowArea.getSize().height));
        blatchMarArrowArea.add(new ArrowPanel(Direction.LEFT, blatchMarArrowArea.getSize().width));
    }

    public void set() {
        JImagePanel aluSetup = new JImagePanel("alu_image.png");
        aluArea.add(aluSetup);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        machineArea = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        mainMemoryLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        memory = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        mar = new javax.swing.JTextField();
        marLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        mbrLabel = new javax.swing.JLabel();
        mbr = new javax.swing.JTextField();
        FootNoteTextField = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        registersLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Register = new javax.swing.JTable();
        abusArrowArea = new javax.swing.JPanel();
        a_busLabel = new javax.swing.JLabel();
        b_busLabel = new javax.swing.JLabel();
        bbusArrowArea = new javax.swing.JPanel();
        alatchArea = new javax.swing.JPanel();
        aLatchLabel = new javax.swing.JLabel();
        alatch = new javax.swing.JTextField();
        blatchArea = new javax.swing.JPanel();
        blatch = new javax.swing.JTextField();
        bLatchLabel = new javax.swing.JLabel();
        blatchArrowArea = new javax.swing.JLayeredPane();
        amuxArea = new javax.swing.JPanel();
        amuxLabel = new javax.swing.JLabel();
        amux = new javax.swing.JTextField();
        alatchArrowArea = new javax.swing.JPanel();
        aluArea = new javax.swing.JPanel();
        alu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        aluShifterArrowArea = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        shifter = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        amuxAluArrowArea = new javax.swing.JLayeredPane();
        alatchArrowArea2 = new javax.swing.JLayeredPane();
        blatchMarArrowArea = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        alatchAmuxArrowArea = new javax.swing.JLayeredPane();
        button1 = new java.awt.Button();
        step = new java.awt.Button();
        button2 = new java.awt.Button();
        End = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        assemblyCodeData = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jCheckBox2 = new javax.swing.JCheckBox();
        Interpreter = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        opcodeArea = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        malArea = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        machineArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable1);

        mainMemoryLabel.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        mainMemoryLabel.setText("Main Memory");

        memory.setBackground(new java.awt.Color(204, 204, 255));
        memory.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        memory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Address", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(memory);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(mainMemoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMemoryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        mar.setEditable(false);
        mar.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        mar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mar.setText("0000 0000 0000");
        mar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marActionPerformed(evt);
            }
        });

        marLabel.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        marLabel.setText("MAR");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(marLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marLabel))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        mbrLabel.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        mbrLabel.setText("MBR");

        mbr.setEditable(false);
        mbr.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        mbr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mbr.setText("0000 0000 0000 0000");
        mbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mbrLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mbr, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(mbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(mbrLabel))
        );

        FootNoteTextField.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        FootNoteTextField.setText("Copyright © 2015 Mong Mary Touch and Thiago Gebrim Goncalves. All rights reserved.");

        registersLabel.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        registersLabel.setText("Registers");

        Register.setBackground(new java.awt.Color(204, 204, 255));
        Register.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        Register.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bit", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Register.getTableHeader().setResizingAllowed(false);
        Register.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(Register);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(registersLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout abusArrowAreaLayout = new javax.swing.GroupLayout(abusArrowArea);
        abusArrowArea.setLayout(abusArrowAreaLayout);
        abusArrowAreaLayout.setHorizontalGroup(
            abusArrowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        abusArrowAreaLayout.setVerticalGroup(
            abusArrowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );

        a_busLabel.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        a_busLabel.setText("A Bus");

        b_busLabel.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        b_busLabel.setText("B Bus");

        javax.swing.GroupLayout bbusArrowAreaLayout = new javax.swing.GroupLayout(bbusArrowArea);
        bbusArrowArea.setLayout(bbusArrowAreaLayout);
        bbusArrowAreaLayout.setHorizontalGroup(
            bbusArrowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        bbusArrowAreaLayout.setVerticalGroup(
            bbusArrowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        aLatchLabel.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        aLatchLabel.setText("A Latch");

        alatch.setEditable(false);
        alatch.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        alatch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alatch.setText("0000 0000 0000 0000");
        alatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alatchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alatchAreaLayout = new javax.swing.GroupLayout(alatchArea);
        alatchArea.setLayout(alatchAreaLayout);
        alatchAreaLayout.setHorizontalGroup(
            alatchAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alatchAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aLatchLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(alatch, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );
        alatchAreaLayout.setVerticalGroup(
            alatchAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alatchAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aLatchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        blatch.setEditable(false);
        blatch.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        blatch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        blatch.setText("0000 0000 0000 0000");
        blatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blatchActionPerformed(evt);
            }
        });

        bLatchLabel.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        bLatchLabel.setText("B Latch");

        javax.swing.GroupLayout blatchAreaLayout = new javax.swing.GroupLayout(blatchArea);
        blatchArea.setLayout(blatchAreaLayout);
        blatchAreaLayout.setHorizontalGroup(
            blatchAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blatchAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(blatch, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(blatchAreaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(bLatchLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        blatchAreaLayout.setVerticalGroup(
            blatchAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blatchAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bLatchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(blatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout blatchArrowAreaLayout = new javax.swing.GroupLayout(blatchArrowArea);
        blatchArrowArea.setLayout(blatchArrowAreaLayout);
        blatchArrowAreaLayout.setHorizontalGroup(
            blatchArrowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        blatchArrowAreaLayout.setVerticalGroup(
            blatchArrowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        amuxLabel.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        amuxLabel.setText("Amux");

        amux.setEditable(false);
        amux.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        amux.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amux.setText("0000 0000 0000 0000");

        javax.swing.GroupLayout amuxAreaLayout = new javax.swing.GroupLayout(amuxArea);
        amuxArea.setLayout(amuxAreaLayout);
        amuxAreaLayout.setHorizontalGroup(
            amuxAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(amuxAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(amux, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amuxLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        amuxAreaLayout.setVerticalGroup(
            amuxAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(amuxAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(amuxAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amuxLabel)))
        );

        javax.swing.GroupLayout alatchArrowAreaLayout = new javax.swing.GroupLayout(alatchArrowArea);
        alatchArrowArea.setLayout(alatchArrowAreaLayout);
        alatchArrowAreaLayout.setHorizontalGroup(
            alatchArrowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        alatchArrowAreaLayout.setVerticalGroup(
            alatchArrowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        alu.setEditable(false);
        alu.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        alu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alu.setText("0000 0000 0000 0000");

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setText("ALU");

        javax.swing.GroupLayout aluShifterArrowAreaLayout = new javax.swing.GroupLayout(aluShifterArrowArea);
        aluShifterArrowArea.setLayout(aluShifterArrowAreaLayout);
        aluShifterArrowAreaLayout.setHorizontalGroup(
            aluShifterArrowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        aluShifterArrowAreaLayout.setVerticalGroup(
            aluShifterArrowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel1.setText("Shifter");

        shifter.setEditable(false);
        shifter.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        shifter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        shifter.setText("0000 0000 0000 0000");
        shifter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shifterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aluAreaLayout = new javax.swing.GroupLayout(aluArea);
        aluArea.setLayout(aluAreaLayout);
        aluAreaLayout.setHorizontalGroup(
            aluAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aluAreaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(aluShifterArrowArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(aluAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aluAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aluAreaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alu, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aluAreaLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shifter, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        aluAreaLayout.setVerticalGroup(
            aluAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluAreaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(aluAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(alu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(aluShifterArrowArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aluAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shifter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout amuxAluArrowAreaLayout = new javax.swing.GroupLayout(amuxAluArrowArea);
        amuxAluArrowArea.setLayout(amuxAluArrowAreaLayout);
        amuxAluArrowAreaLayout.setHorizontalGroup(
            amuxAluArrowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        amuxAluArrowAreaLayout.setVerticalGroup(
            amuxAluArrowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout alatchArrowArea2Layout = new javax.swing.GroupLayout(alatchArrowArea2);
        alatchArrowArea2.setLayout(alatchArrowArea2Layout);
        alatchArrowArea2Layout.setHorizontalGroup(
            alatchArrowArea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        alatchArrowArea2Layout.setVerticalGroup(
            alatchArrowArea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout blatchMarArrowAreaLayout = new javax.swing.GroupLayout(blatchMarArrowArea);
        blatchMarArrowArea.setLayout(blatchMarArrowAreaLayout);
        blatchMarArrowAreaLayout.setHorizontalGroup(
            blatchMarArrowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );
        blatchMarArrowAreaLayout.setVerticalGroup(
            blatchMarArrowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout alatchAmuxArrowAreaLayout = new javax.swing.GroupLayout(alatchAmuxArrowArea);
        alatchAmuxArrowArea.setLayout(alatchAmuxArrowAreaLayout);
        alatchAmuxArrowAreaLayout.setHorizontalGroup(
            alatchAmuxArrowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        alatchAmuxArrowAreaLayout.setVerticalGroup(
            alatchAmuxArrowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout machineAreaLayout = new javax.swing.GroupLayout(machineArea);
        machineArea.setLayout(machineAreaLayout);
        machineAreaLayout.setHorizontalGroup(
            machineAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(machineAreaLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(machineAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(machineAreaLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(machineAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(machineAreaLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(machineAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(a_busLabel)
                                    .addGroup(machineAreaLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(abusArrowArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(130, 130, 130)
                                .addGroup(machineAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b_busLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(machineAreaLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(bbusArrowArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(machineAreaLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(machineAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(machineAreaLayout.createSequentialGroup()
                                        .addComponent(alatchArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(blatchArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(machineAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(machineAreaLayout.createSequentialGroup()
                                            .addComponent(amuxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(60, 60, 60))
                                        .addGroup(machineAreaLayout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(machineAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(aluArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(machineAreaLayout.createSequentialGroup()
                                                    .addGap(27, 27, 27)
                                                    .addComponent(amuxAluArrowArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(123, 123, 123)
                                                    .addComponent(blatchArrowArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addGap(99, 99, 99)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(machineAreaLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(machineAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(machineAreaLayout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blatchMarArrowArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alatchAmuxArrowArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(868, 868, 868)
                        .addComponent(alatchArrowArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alatchArrowArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(machineAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FootNoteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        machineAreaLayout.setVerticalGroup(
            machineAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(machineAreaLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(machineAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(machineAreaLayout.createSequentialGroup()
                        .addGroup(machineAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a_busLabel)
                            .addComponent(b_busLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(machineAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(machineAreaLayout.createSequentialGroup()
                                .addGroup(machineAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(abusArrowArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bbusArrowArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(machineAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blatchArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alatchArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(machineAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(machineAreaLayout.createSequentialGroup()
                                .addGroup(machineAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alatchArrowArea2)
                                    .addGroup(machineAreaLayout.createSequentialGroup()
                                        .addGroup(machineAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(alatchAmuxArrowArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(machineAreaLayout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(blatchMarArrowArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(amuxArea, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(amuxAluArrowArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(blatchArrowArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aluArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(machineAreaLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(FootNoteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alatchArrowArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        button1.setLabel("LOAD");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        step.setLabel("Full Cycle");
        step.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepActionPerformed(evt);
            }
        });

        button2.setLabel("Subcycle");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        End.setLabel("button3");
        End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(machineArea, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(step, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(End, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(565, 565, 565))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(step, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(machineArea, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MIC1 Deisgn", jPanel3);

        jLabel3.setText("Assembly Code");

        assemblyCodeData.setColumns(20);
        assemblyCodeData.setRows(5);
        assemblyCodeData.setText("OP1: 30\nOP2: 50\nANS: 0\nLODD OP1:\nADDD OP2:\nSTOD ANS:\nHALT");
        jScrollPane1.setViewportView(assemblyCodeData);

        jLabel6.setText("Supported Assembly Instruction Set");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"LODD", "0000", "xxxxxxxxxxxx"},
                {"STOD", "0001", "xxxxxxxxxxxx"},
                {"ADDD", "0010", "xxxxxxxxxxxx"},
                {"SUBD", "0011", "xxxxxxxxxxxx"},
                {"JPOS", "0100", "xxxxxxxxxxxx"},
                {"JZER", "0101", "xxxxxxxxxxxx"},
                {"JUMP", "0110", "xxxxxxxxxxxx"},
                {"LOCO", "0111", "xxxxxxxxxxxx"},
                {"LODL", "1000", "xxxxxxxxxxxx"},
                {"STOL", "1001", "xxxxxxxxxxxx"},
                {"ADDL", "1010", "xxxxxxxxxxxx"},
                {"SUBL", "1011", "xxxxxxxxxxxx"},
                {"JNEG", "1100", "xxxxxxxxxxxx"},
                {"JNZE", "1101", "xxxxxxxxxxxx"},
                {"CALL", "1110", "xxxxxxxxxxxx"},
                {"PSHI", "1111000000000000", null},
                {"POPI", "1111001000000000", null},
                {"PUSH", "1111010000000000", null},
                {"POP", "1111011000000000", null},
                {"RETN", "1111100000000000", null},
                {"SWAP", "1111101000000000", null},
                {"INSP", "11111100", "yyyyyyyy"},
                {"DESP", "11111110", "yyyyyyyy"}
            },
            new String [] {
                "Instruction", "Operand", "Argument"
            }
        ));
        jScrollPane7.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(15);
            jTable2.getColumnModel().getColumn(1).setMinWidth(90);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(90);
            jTable2.getColumnModel().getColumn(2).setMinWidth(10);
        }

        jCheckBox2.setText("Modify");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 131, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 211, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Assembly Level", jPanel1);

        opcodeArea.setEditable(false);
        opcodeArea.setBackground(new java.awt.Color(204, 255, 204));
        opcodeArea.setColumns(20);
        opcodeArea.setFont(new java.awt.Font("Serif", 0, 13)); // NOI18N
        opcodeArea.setRows(5);
        jScrollPane8.setViewportView(opcodeArea);

        malArea.setColumns(20);
        malArea.setFont(new java.awt.Font("Serif", 0, 13)); // NOI18N
        malArea.setRows(5);
        malArea.setText("0:mar := pc; rd; \n1:pc := 1 + pc; rd; \n2:ir := mbr; if n then goto 28; \n3:tir := lshift(ir + ir); if n then goto 19; \n4:tir := lshift(tir); if n then goto 11; \n5:alu := tir; if n then goto 9; \n6:mar := ir; rd; \n7:rd; \n8:ac := mbr; goto 0; \n9:mar := ir; mbr := ac; wr; \n10:wr; goto 0; \n11:alu := tir; if n then goto 15; \n12:mar := ir; rd; \n13:rd; \n14:ac := ac + mbr; goto 0; \n15:mar := ir; rd; \n16:ac := 1 + ac; rd; \n17:a := inv(mbr); \n18:ac := a + ac; goto 0; \n19:tir := lshift(tir); if n then goto 25; \n20:alu := tir; if n then goto 23; \n21:alu := ac; if n then goto 0; \n22:pc := band(ir, amask); goto 0; \n23:alu := ac; if z then goto 22; \n24:goto 0; \n25:alu := tir; if n then goto 27; \n26:pc := band(ir, amask); goto 0; \n27:ac := band(ir, amask); goto 0; \n28:tir := lshift(ir + ir); if n then goto 40; \n29:tir := lshift(tir); if n then goto 35; \n30:alu := tir; if n then goto 33; \n31:a := sp + ir; \n32:mar := a; rd; goto 7; \n33:a := sp + ir; \n34:mar := a; mbr := ac; wr; goto 10; \n35:alu := tir; if n then goto 38; \n36:a := sp + ir; \n37:mar := a; rd; goto 13; \n38:a := sp + ir; \n39:mar := a; rd; goto 16; \n40:tir := lshift(tir); if n then goto 46; \n41:alu := tir; if n then goto 44; \n42:alu := ac; if n then goto 22; \n43:goto 0; \n44:alu := ac; if z then goto 0; \n45:pc := band(ir, amask); goto 0; \n46:tir := lshift(tir); if n then goto 50; \n47:sp := sp + (-1); \n48:mar := sp; mbr := pc; wr; \n49:pc := band(ir, amask); wr; goto 0; \n50:tir := lshift(tir); if n then goto 65; \n51:tir := lshift(tir); if n then goto 59; \n52:alu := tir; if n then goto 56; \n53:mar := ac; rd; \n54:sp := sp + (-1); rd; \n55:mar := sp; wr; goto 10; \n56:mar := sp; sp := sp + 1; rd; \n57:rd; \n58:mar := ac; wr; goto 10; \n59:alu := tir; if n then goto 62; \n60:sp := sp + (-1); \n61:mar := sp; mbr := ac; wr; goto 10; \n62:mar := sp; sp := sp + 1; rd; \n63:rd; \n64:ac := mbr; goto 0; \n65:tir := lshift(tir); if n then goto 73; \n66:alu := tir; if n then goto 70; \n67:mar := sp; sp := sp + 1; rd; \n68:rd; \n69:pc := mbr; goto 0; \n70:a := ac; \n71:ac := sp; \n72:sp := a; goto 0; \n73:alu := tir; if n then goto 76; \n74:a := band(ir, smask); \n75:sp := sp + a; goto 0; \n76:tir := tir + tir; if n then goto 80; \n77:a := band(ir, smask); \n78:a := inv(a); \n79:a := a + 1; goto 75; \n80:rd; wr; ");
        malArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                malAreaKeyPressed(evt);
            }
        });
        jScrollPane9.setViewportView(malArea);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
            .addComponent(jScrollPane8)
        );

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setText("MAL(Micro-Assembly Language) Instruction");

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setText("Interpreter Opcode");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(108, 108, 108)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 83, Short.MAX_VALUE))
        );

        jCheckBox1.setText("Modify");

        javax.swing.GroupLayout InterpreterLayout = new javax.swing.GroupLayout(Interpreter);
        Interpreter.setLayout(InterpreterLayout);
        InterpreterLayout.setHorizontalGroup(
            InterpreterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterpreterLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(InterpreterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InterpreterLayout.setVerticalGroup(
            InterpreterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InterpreterLayout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("MAL Level", Interpreter);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

        MIC1 mic = new MIC1();
        Thread test_runner = new Thread(mic);
        test_runner.start();
        MIC1.fullCycle = true;
    }//GEN-LAST:event_button1ActionPerformed

    private void stepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepActionPerformed
        MIC1.fullCycle = true;
        MIC1.step = false;
        synchronized (objectLock) {
            objectLock.notify();
        }

// TODO add your handling code here:
    }//GEN-LAST:event_stepActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        MIC1.fullCycle = false;
        MIC1.step = true;
        synchronized (objectLock) {
            objectLock.notify();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndActionPerformed
        MIC1.fullCycle = false;
        MIC1.step = false;
        synchronized (objectLock) {
            objectLock.notify();
        }
    }//GEN-LAST:event_EndActionPerformed

    private void marActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marActionPerformed

    private void mbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbrActionPerformed

    private void alatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alatchActionPerformed

    private void blatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blatchActionPerformed

    private void shifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shifterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shifterActionPerformed

    private void malAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_malAreaKeyPressed
        char c = evt.getKeyChar();
        int count = 0;
        boolean invalid = false;

        if (c == KeyEvent.VK_ENTER) {
            opcodeArea.setText("");

            for (String line : malArea.getText().split("\\n")) {
                opCodeAnswer = instructs.decode(line);
                if (opCodeAnswer.equals("00000000000000000000000000000000")) {
                    JOptionPane.showMessageDialog(this, "Invalid Instruction:\n" + line);
                    invalid = true;
                    break;
                }
                addLineNumber = true;
                opcodeArea.append(opCodeAnswer + "\n");
                count++;
            }
        }
    }//GEN-LAST:event_malAreaKeyPressed

    private String formatMalArea(String string) {
        String formatLine = string;
        String[] stringArray = formatLine.split("\\n");
        System.out.println(string);
        String newString = "";
        int i = 0;
        int neg = 0;
        for (i = 0; i < stringArray.length; i++) {

            String[] temp_array = stringArray[i].split(":");
            if (temp_array.length > 1) {
                String formattedStr = StringBuilder(temp_array, 1);
                newString += i + ":" + formattedStr + "\n";
            } else {
                neg++;
            }
        }

        return newString + (i - neg) + ":";
    }

    private String StringBuilder(String[] str_data, int index) {
        String return_str = "";
        int i;
        for (i = index; i < str_data.length; i++) {
            return_str += str_data[i];
            if ((i != str_data.length - 1)) {
                return_str += ":";
            }
        }
        return return_str;
    }

    private void checkFormatMal() {
        malArea.setText(buildString(malArea.getText().split("\\n")));
    }

    private String buildString(String[] array) {
        String newString = "";
        for (int i = 0; i < array.length - 1; i++) {
            newString += array[i] + "\n";
        }
        return newString;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI().setVisible(true);
            }
        });
        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button End;
    private javax.swing.JLabel FootNoteTextField;
    private javax.swing.JPanel Interpreter;
    public static javax.swing.JTable Register;
    private javax.swing.JLabel aLatchLabel;
    private javax.swing.JLabel a_busLabel;
    private javax.swing.JPanel abusArrowArea;
    public static javax.swing.JTextField alatch;
    private javax.swing.JLayeredPane alatchAmuxArrowArea;
    private javax.swing.JPanel alatchArea;
    private javax.swing.JPanel alatchArrowArea;
    private javax.swing.JLayeredPane alatchArrowArea2;
    public static javax.swing.JTextField alu;
    private javax.swing.JPanel aluArea;
    private javax.swing.JLayeredPane aluShifterArrowArea;
    public static javax.swing.JTextField amux;
    private javax.swing.JLayeredPane amuxAluArrowArea;
    private javax.swing.JPanel amuxArea;
    private javax.swing.JLabel amuxLabel;
    public static javax.swing.JTextArea assemblyCodeData;
    private javax.swing.JLabel bLatchLabel;
    private javax.swing.JLabel b_busLabel;
    private javax.swing.JPanel bbusArrowArea;
    public static javax.swing.JTextField blatch;
    private javax.swing.JPanel blatchArea;
    private javax.swing.JLayeredPane blatchArrowArea;
    private javax.swing.JLayeredPane blatchMarArrowArea;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel machineArea;
    private javax.swing.JLabel mainMemoryLabel;
    private javax.swing.JTextArea malArea;
    public static javax.swing.JTextField mar;
    private javax.swing.JLabel marLabel;
    public static javax.swing.JTextField mbr;
    private javax.swing.JLabel mbrLabel;
    public static javax.swing.JTable memory;
    public static javax.swing.JTextArea opcodeArea;
    private javax.swing.JLabel registersLabel;
    public static javax.swing.JTextField shifter;
    private java.awt.Button step;
    // End of variables declaration//GEN-END:variables
}
